[package]
name = "bakatsugi-payload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.53"
goblin = "0.4.3"
cargo-emit = "0.2.1"
const-gen = "1.0.0"
